# Build settings
baseurl: 
markdown: kramdown
permalink: /:title/
keywords: Aqua Deepp Music, psychedelic, psytrance

port: 7666

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded
