# Build settings
baseurl: 
markdown: kramdown
permalink: /:title/

host: 0.0.0.0
port: 7003

exclude: ['README.md']

sass:
  sass_dir: assets/css
  style: :expanded

# custom settings
keywords: 'Aqua Deepp Music, psychedelic, psytrance'
